/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'parentsName' : IDL.Text,
  'childsName' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
  'childsAge' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllSubmissionsSortedByTimestamp' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'parentsName' : IDL.Text,
    'childsName' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
    'childsAge' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllSubmissionsSortedByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };